index=main sourcetype=_json _index_earliest=-1m
| eval decoded_traffic=urldecode(_raw)
| where match(decoded_traffic, "(?i)(nmap|masscan|nikto|burpsuite|sqlmap|acunetix|dirb|zaproxy|nessus)")
| table _time, _raw
