index=main sourcetype=_json _index_earliest=-1m
| eval decoded_ssrf=urldecode(_raw)
| where match(decoded_ssrf, "(?i)(localhost|127\.\d+\.\d+\.\d+|169\.254\.\d+\.\d+|0\.0\.0\.0|::1|10\.\d+\.\d+\.\d+|192\.168\.\d+\.\d+)")
| table _time, _raw
