name: Deploy Rules to Splunk

on:
  push:
    branches:
      - main
    paths:
      - 'rules/splunk/**'
      - 'deploy_to_splunk.py'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests urllib3

      - name: Run Splunk Deployment Script
        run: python deploy_to_splunk.py
